### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mdsumner** [diminutive/insideclipper#1]
this is currently the parent package ...

* insidesp - embeds the actual code used in sp (ORourke + SEXP plus some pretty arcane old R API)
** C: InPoly(), point_in_polygon_old_sp()
** R: inside_sp()
* insidesexp - calls ORourke C, depends on using old R API (just my reading of the R API)
** C: InPoly(), InPoly_C()
** R: inside_sexp
* insidecgal - calls CGAL, depends on cpp11, has a loop mat given the way I was testing performance
** C: point_in_polygon_cgal(), insidecgal_loop_mat()
** R: point_in_polygon_cgal(), insidecgal_loop_mat()
* insideclipper - calls clipper.h, depends on cpp11
** C: InPoly_clipper(), inside_loop_xy(), inside_point_cull(), inside_loop_mat()
** R: ic_over(), inside_clipper(), inside_clipper_loop_x_y(), inside_clipper_loop_mat()
* insidecp11 - calls ORourke C++, depends on cpp11
** C: InPoly(), InPoly_cpp()
** R: inside_cpp11()

- [ ] combine insideclipper and insidecpp11 (so they are really just a headers ? clipper and orourke)
- [ ] clean up insidesp, so it's faithful to the sp impl but without unused code (currently only has the point in ring code)
- [ ] determine naming scheme/s in C++ and in R
- [ ] insider - parent package
